
name: run generate_todo.py

on:
  schedule:
     - cron: '0 2 * * 1' # At 02:00 on Monday
  push:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Pull
        run: |
          git pull

      - name: Clean
        run: |
          touch out/a.pdf
          rm out/*.pdf -f
          git rm out/*.pdf --cached

      - name: Run script
        run: |
          python generate_todo.py
          
      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)

      - name: Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: main 
          github_token: ${{ secrets.GITHUB_TOKEN }}
