name: run generate_todo.py

on:
  schedule:
     #- cron: '0 2 * * 1' # At 02:00 on Monday
     - cron: '0-59/5 * * * *'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pypdf
          pip install pyyaml
          pip install reportlab
          
      - name: Run script
        run: |
          python generate_todo.py
          
      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          git push
      #- name: Push
       # uses: ad-m/github-push-action@v0.6.0
        #with:
         # branch: main 
